name: build mpv
on:
  workflow_dispatch:
    inputs:
      enableLto:
        description: 'enable LTO'
        required: false
        default: false
        type: boolean
        
jobs:
  build:
    runs-on: windows-latest

    env: 
      USERNAME: ikas-mc
      FEED_URL: https://nuget.pkg.github.com/ikas-mc/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ikas-mc/index.json,readwrite"
      ENABLE_LTO: ${{ github.event.inputs.enableLto }}

    steps:
    - uses: actions/checkout@v4
    
    - name: msvc
      uses: microsoft/setup-msbuild@v2

    - name: Add NuGet sources
      shell: pwsh
      run: |
        .$(vcpkg.exe fetch nuget) `
          sources add `
          -Source "${{ env.FEED_URL }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.USERNAME }}" `
          -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
        .$(vcpkg.exe fetch nuget) `
          setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" `
          -Source "${{ env.FEED_URL }}"

    - name: tools
      run: |
        python -m pip install meson
        pip3 install jinja2
        mkdir pkg-config
        tar -xvf "deps\mingw-w64-x86_64-pkgconf-1~2.5.1-1-any.pkg.tar" -C pkg-config

    - name: build deps
      run: |
        $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' -and `
                                                           $_ -ne 'C:\Program Files\CMake\bin' -and `
                                                           $_ -ne 'C:\Strawberry\c\bin' }) -join ';'
        $env:VS_ROOT="C:\Program Files\Microsoft Visual Studio\18\Enterprise"
        $env:VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT
        if ($env:ENABLE_LTO -eq 'true') {
          .\build-deps-lto.ps1
        } else {
          .\build-deps.ps1
        }

    - name: build mpv
      run: |
        $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' -and `
                                                           $_ -ne 'C:\Program Files\CMake\bin' -and `
                                                           $_ -ne 'C:\Strawberry\c\bin' }) -join ';'
        $env:VS_ROOT="C:\Program Files\Microsoft Visual Studio\18\Enterprise"
        if ($env:ENABLE_LTO -eq 'true') {
          .\build-mpv-lto.ps1
        } else {
          .\build-mpv.ps1
        }

    - name: Print build log
      if: ${{ failure() && steps.build.outcome == 'failure' }}
      run: |
        cat ./app/build/meson-logs/meson-log.txt

    - name: upload mpv.exe
      uses: actions/upload-artifact@v4
      with:
        name: mpv.exe
        path: |
          mpv-builder\mpv-windows\build\mpv-windows-x64\bin\mpv.exe
          mpv-builder\mpv-windows\build\mpv-windows-x64\bin\mpv.pdb
          mpv-builder\mpv-windows\build\mpv-windows-x64\share\doc
          mpv-builder\mpv-windows\build\mpv-windows-x64\share\metainfo

    - name: upload mpv-2.dll
      uses: actions/upload-artifact@v4
      with:
        name: mpv-2.dll
        path: |
          mpv-builder\mpv-windows\build\mpv-windows-x64\bin\mpv-2.dll
          mpv-builder\mpv-windows\build\mpv-windows-x64\bin\mpv-2.pdb
          mpv-builder\mpv-windows\build\mpv-windows-x64\include
          mpv-builder\mpv-windows\build\mpv-windows-x64\lib
          mpv-builder\mpv-windows\build\mpv-windows-x64\share
